### ISSUE TITLE
Call the dataloader.py code in the daily data generation and save the dictionaries to json files

### ISSUE THREAD

**Issue by ianknowles** [OxfordDemSci/gwasdiversitymonitor#21]
Dataloader converts the input csv files to a json format for use by the javascript, at present this json is generated whenever the application regenerates the html from the template files, but the data does not update this frequently it only changes with changes to the csv files. Generating the json is unnecessary additional overhead on page loads.

The generated json objects are then written directly into the html via the index template, this is further overhead to page loads but it also creates an oversized html file, currently 30 MiB approx uncompressed. Such a large html file takes longer to transfer, longer for the DOM to load, and puts so much data in the DOM that browser dev tools may crash on viewing it. The delay in DOM loading has been observed at 0.3 seconds on one machine but over 6 seconds on another. This contributes to the unresponsiveness of the page, recommended design principles are to ensure fast loading of the DOM and to delay further rendering and network requests while showing progress indicators so the user can interact with the page while resource loading finishes.

The large size of the DOM may potentially impact the javascript which heavily relies on DOM editing to render the graphs as svgs, this may be somewhat mitigated by the objects typically searched for appearing above the json data in the DOM tree.

Inserting small snippets of json directly into the html is intended to reduce network requests and speed up resource loading but this is only possible when the json data is a small number of nodes that does not significantly impact the html size. With 30 MiB of data this needs to be sent as a seperate file. The dataloader code should be called by the daily data task and the json objects then saved as json files in the same location as the csv files. The javascript will then fetch the json as a network request (#22).

**Comment by crahal** [comment]
Implemented in [031aeee](https://github.com/OxfordDemSci/gwasdiversitymonitor/commit/031aeee1fd2a0c1604560a6da579d3a36af8b6ce), outputting corresponding filenames to `routes.py` and output to `app/toplot/*.json`. Please review and merge as appropriate!
