### ISSUE TITLE
Requirements.txt is out of date

### ISSUE THREAD

**Issue by ianknowles** [OxfordDemSci/gwasdiversitymonitor#29]
Module Freeze has been removed from PyPi for a long time, all the core modules need updating. Its not currently possible to launch the project by fetching everything from requirements.txt without a little tinkering and manual updates.

**Comment by studiovincentstraub** [comment]
Attempting to launch the project locally by first running `python generate_data.py` still results in multiple `ModuleNotFound` errors and requires manual updates and installation of the following modules: 
- `unicodedata2`
- `joblib`
- `biopython`
- `Flask-Cache`
- `matplotlib`
- `tqdm`
- `PyLaTeX`

**Comment by crahal** [comment]
Thanks @vincejstraub and @doug-leasure: Closed with [b44abce](https://github.com/OxfordDemSci/gwasdiversitymonitor/commit/b44abce30e50f13366c16f27c0cfe0320ff19bab).
