### ISSUE TITLE
Unable to run app locally because of missing files

### ISSUE THREAD

**Issue by jdblischak** [OxfordDemSci/gwasdiversitymonitor#37]
Thanks for creating this great resource. I was having difficulty interacting with the web application (the main issue was the bubble plot), so I wanted to run it locally. I followed the instructions in the README, but the app throws errors about missing data, e.g.

```
FileNotFoundError: [Errno 2] No such file or directory: 'app/data/toplot/doughnutGraph.json'
FileNotFoundError: [Errno 2] No such file or directory: 'app/data/toplot/bubbleGraph.json'
FileNotFoundError: [Errno 2] No such file or directory: 'app/data/toplot/heatMap.json'
FileNotFoundError: [Errno 2] No such file or directory: 'app/data/toplot/ancestriesOrdered.json'
```

Am I missing a setup step?

**Steps to reproduce what I am observing:**

* Clone repo

```
git clone git@github.com:OxfordDemSci/gwasdiversitymonitor.git
cd gwasdiversitymonitor
```

* Create a conda env and install updated dependencies (#29, #35)

```
conda create -y -n gdm python
conda activate gdm
pip install -r https://raw.githubusercontent.com/Smilin-Dominator/gwasdiversitymonitor/requirements-upgrade/requirements.txt
```

* Run the app

```
python gwasdiversitymonitor.py
```

* Open the app at http://localhost:5000/

**Attempt to fix it**

I assumed that maybe I needed to pre-download the data with `python app/generate_data.py`. I ran it from the root of the project (as explained in #31). But it appeared to have no effect. It ran without error, there was no output, and `git status` showed no updated files. None of the missing files were added to `app/data/toplot/`

```
$ ls app/data/toplot
bubble_df.csv			heatmap_count_replication.csv	ts1_initial_sum.csv		ts2_initial_sum.csv
choro_df.csv			heatmap_sum_initial.csv		ts1_replication_count.csv	ts2_replication_count.csv
doughnut_df.csv			heatmap_sum_replication.csv	ts1_replication_sum.csv		ts2_replication_sum.csv
heatmap_count_initial.csv	ts1_initial_count.csv		ts2_initial_count.csv
```

**Comment by crahal** [comment]
Hi, thanks for this! Yes, we absolutely need to run `python app/generate_data.py`; I can't quite replicate this error with your MWE though unfortunately. Can you post the contents of `app/logging/diversity_logger.log`?

I'm going to leave this issue open: if you wanted to make a pull request which checks for the existance of the necessary files when launching the app, I'd be keen to review it and close the issue!

**Comment by jdblischak** [comment]
> I can't quite replicate this error with your MWE though unfortunately. Can you post the contents of `app/logging/diversity_logger.log`?

Thanks for the tip. That helped me solve the problem. The downloads all failed because I was connected to my company's VPN. After I disconnected, I was able to download the data with the `python app/generate_data.py`.

```
$ cat app/logging/diversity_logger.log
2022-01-21 09:36:12,905 - diversity_logger - INFO - final year is being set to: 2021
2022-01-21 09:36:13,586 - diversity_logger - DEBUG - Problem downloading Catalog data!HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Max retries exceeded with url: /gwas/api/search/downloads/studies_alternative (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
2022-01-21 09:36:13,590 - diversity_logger - DEBUG - Clean of the raw GWAS Catalog datasets: Failed -- [Errno 2] No such file or directory: '/private/tmp/gdm/app/data/catalog/raw/Cat_Stud.tsv'
2022-01-21 09:36:13,591 - diversity_logger - DEBUG - Build of the bubble datasets: Failed -- [Errno 2] No such file or directory: '/private/tmp/gdm/app/data/catalog/raw/Cat_Stud.tsv'
2022-01-21 09:36:13,591 - diversity_logger - DEBUG - Build of the doughnut datasets: Failed -- [Errno 2] No such file or directory: '/private/tmp/gdm/app/data/catalog/raw/Cat_Stud.tsv'
2022-01-21 09:36:13,592 - diversity_logger - DEBUG - generate_data.py failed, uncaught error: [Errno 2] No such file or directory: '/private/tmp/gdm/app/data/catalog/synthetic/Cat_Anc_wBroader.tsv'
```

> make a pull request which checks for the existance of the necessary files when launching the app (and then runs generate_data.py if no files)

Running the script isn't too bad. The problem is that the step is undocumented, and the error messages are invisibly logged (ie unless you know to look at the log file, you have no idea that something went wrong). How about a PR with the following:

1. Document the `generate_data.py` step in the README
2. If the data script fails, send a message to the user to check the log file

https://github.com/OxfordDemSci/gwasdiversitymonitor/blob/1ad9dcbe229603e307af93061662c23a35cfe3a0/app/generate_data.py#L961-L962

**Comment by crahal** [comment]
Hi, thanks! This looks great! Sorry for the slow reply. My only suggestion would be to catch this as a `FileNotFoundError` maybe? Perhaps try: except FileNotFound, finally (other stuff)? If you can do this and make a PR I'll review and accept immediately :)

**Comment by jdblischak** [comment]
I opened PR #40 to continue the conversation.

> My only suggestion would be to catch this as a FileNotFoundError maybe? Perhaps try: except FileNotFound, finally (other stuff)? 

Could you please elaborate on your suggestion? I don't fully understand. I could catch the exception with `try` and `except`, but I'd end up writing an error message very similar to the default of `FileNotFoundError: [Errno 2] No such file or directory: 'app/data/toplot/ancestriesOrdered.json'`. Do you want me to write something like: `Missing the file 'app/data/toplot/ancestriesOrdered.json'. Please run app/generate_data.py to download required data files`? Also, what were you thinking I would include in the `finally` block?

**Comment by crahal** [comment]
Ah, your solution is even better than that which I had in mind; going to close this issue for now! It might be that we can re-open a similar one in the future which checks for the existance of all of the necessary json files. Thank you again!
