### ISSUE TITLE
gwas_cron container running repeatedly

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/gwasdiversitymonitor#56]
The gwas_cron container is executing generate_data.py then restarting immediately and running it again. This is causing the cpu resources on the LightSail instance to be in the "burstable zone" most of the time. 

The problem is in the command launching the docker container: 
https://github.com/OxfordDemSci/gwasdiversitymonitor/blob/master/docker-compose.yml#L40

It should execute generate_data.py and then launch cron in the foreground. The persistent foreground process is intended to prevent the container from stopping. It does not appear to be launching cron in the foreground which causes the container to stop and then restart because it's restart policy is defined as `restart: unless-stopped` here:
https://github.com/OxfordDemSci/gwasdiversitymonitor/blob/master/docker-compose.yml#L45

Two potential solutions:
1. Create a launch shell script with these two commands rather than running them in series from the docker-compose file
2. Set the restart policy on the gwas_cron container to `restart: on-failure` and then setup the crontab on the virtual machine to run `cd ~/gwasdiversitymonitor; docker-compose up -d --build gwas_cron` @daily.

**Comment by crahal** [comment]
Closed with [5410888](https://github.com/OxfordDemSci/gwasdiversitymonitor/commit/5410888bc98742a3cdcd614f40db17fc105ac052). Thanks Doug!
