### ISSUE TITLE
Downloading data triggers figure download

### ISSUE THREAD

**Issue by crahal** [OxfordDemSci/gwasdiversitymonitor#60]
Attemping to download the data also triggers the downloading of the figures, which it likely shouldnt as there's a seperate icon for downloading the figures.

**Comment by quentinGI** [comment]
Issue will be fixed once this branch will be merged. (still pending GI functional review and business review)
https://github.com/OxfordDemSci/gwasdiversitymonitor/pull/62

**Comment by doug-leasure** [comment]
Resolved with PR #73
